using UnityEngine;

namespace NWH.VehiclePhysics
{
    /// <summary>
    /// Skid smoke and surface dust generated by wheel slipping / rolling over the surface.
    /// </summary>
    [System.Serializable]
    public class SurfaceParticles
    {
        public ParticleSystem smoke;
        public ParticleSystem dust;
		private Material dustMat;

		private ParticleSystem dustSub;
		private Material dustSubMat;

		private Color dustColor = Color.white;
		private Color dustSubColor = Color.white;

        public GameObject smokeGo;
        public GameObject dustGo;

        private float smokeEmissionRate;
        private float smokeEmissionRateVelocity;
        private float dustEmissionRate;
		private float dustSubEmissionRate;

        private float forwardSmokeCoeff = 10f;
        private float sideSmokeCoeff = 10f;

        private VehicleController vc;
        private Wheel wheel;

        private GroundDetection.GroundEntity groundEntity;
        private GroundDetection.GroundEntity prevGroundEntity;


        public void Initialize(VehicleController vc, Wheel wheel)
        {
            this.vc = vc;
            this.wheel = wheel;

            // Initialize skid smoke
            if (vc.groundDetection.smokePrefab != null)
            {
                smokeGo = GameObject.Instantiate(vc.groundDetection.smokePrefab);
                smokeGo.transform.parent = wheel.ControllerTransform;
                smokeGo.transform.position = wheel.VisualTransform.position - wheel.VisualTransform.up * wheel.Radius
                    + vc.transform.forward * wheel.Radius;
                smoke = smokeGo.GetComponent<ParticleSystem>();

                var shape = smoke.shape;
                shape.radius = wheel.Width * 1.5f;
            }
            else
            {
                Debug.LogWarning("Smoke Prefab is null, wheel slip will not produce smoke.");
            }

            // Initialize ground dust
            if (vc.groundDetection.dustPrefab != null)
            {
                dustGo = GameObject.Instantiate(vc.groundDetection.dustPrefab);
                dustGo.transform.parent = wheel.ControllerTransform;
                dustGo.transform.position = wheel.VisualTransform.position;

                dust = dustGo.GetComponent<ParticleSystem>();
				dustMat = dust.GetComponent<Renderer>().material;
				dustColor = dustMat.GetColor("_BaseColor");

				foreach (ParticleSystem p in dustGo.GetComponentsInChildren<ParticleSystem>())
				{
					if (p == dust) continue;

					dustSub = p;
					dustSubMat = p.GetComponent<Renderer>().material;
					dustSubColor = dustSubMat.GetColor("_BaseColor");
				}
            }
            else
            {
                Debug.LogWarning("Dust Prefab is null, there will be no surface dust.");
            }
        }

        public void Update()
        {
            groundEntity = vc.groundDetection.GetCurrentGroundEntity(wheel.WheelController);

            // Update skid smoke
            if (smoke != null)
            {
                float forwardSmokeStrength = Mathf.Clamp01(wheel.ForwardSlip - vc.forwardSlipThreshold) * forwardSmokeCoeff;
                float sideSmokeStrength = Mathf.Clamp01(wheel.SideSlip - vc.sideSlipThreshold * 3f) * sideSmokeCoeff;

                if (wheel.SmoothRPM < 100f)
                {
                    forwardSmokeStrength = 0;
                }

                float newSmokeEmissionRate = 0f;
                if (groundEntity != null && wheel.IsGrounded && (wheel.HasForwardSlip || wheel.HasSideSlip) && prevGroundEntity == groundEntity)
                {
                    newSmokeEmissionRate = groundEntity.smokeIntensity * Mathf.Clamp01(forwardSmokeStrength + sideSmokeStrength);
                    smokeEmissionRate = Mathf.SmoothDamp(smokeEmissionRate, newSmokeEmissionRate, ref smokeEmissionRateVelocity, 4f);
                }
                else
                {
                    smokeEmissionRate = newSmokeEmissionRate;
                }

                float distanceBias = Mathf.Clamp01(Mathf.Abs(vc.ForwardVelocity) / 3f);
                var smokeEmission = smoke.emission;
                smokeEmission.rateOverDistance = distanceBias * smokeEmissionRate;
                smokeEmission.rateOverTime = (1f - distanceBias) * smokeEmissionRate;
            }

			// Update ground dust
			if (dust != null)
			{
				var dustEmission = dust.emission;
				var dustSubEmission = dustSub.emission;
				if (groundEntity != null)
				{
					dustEmissionRate = 0f;
					dustSubEmissionRate = 0f;

					if (wheel.IsGrounded)
					{
						dustEmissionRate = Mathf.Clamp01(vc.Speed / 12f);
						dustSubEmissionRate = Mathf.Clamp01(vc.Speed / 12.0f);

						var main = dust.main;
						var sub = dustSub.main;

						//main.startColor = groundEntity.dustColor;
						//sub.startColor = groundEntity.dustColor;
						//dustSubMat.color = groundEntity.dustColor;

						dustColor = new Color
						(
							groundEntity.dustColor.r,
							groundEntity.dustColor.g,
							groundEntity.dustColor.b,
							dustColor.a
						);
						dustSubColor = new Color
						(
							groundEntity.dustColor.r,
							groundEntity.dustColor.g,
							groundEntity.dustColor.b,
							dustSubColor.a
						);

						dustMat.SetColor("_BaseColor", dustColor);
						dustSubMat.SetColor("_BaseColor", dustSubColor);
						sub.startSpeedMultiplier = Mathf.Abs(vc.Speed);
					}

					dustEmission.rateOverDistance = dustEmissionRate * groundEntity.dustIntensity * 0.1f;
					dustSubEmission.rateOverDistance = dustSubEmissionRate * groundEntity.dustIntensity * 0.2f;
				}
				else
				{
					dustEmission.rateOverDistance = 0f;
					dustSubEmission.rateOverDistance = 0f;
				}
			}

			prevGroundEntity = groundEntity;
        }
    }
}